# Generated by Django 3.0.2 on 2020-02-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
